---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: longhorn-ui-auth
    nginx.ingress.kubernetes.io/auth-realm: "Longhorn UI"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ longhorn_ui_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
