---
common_packages:
  - curl
  - jq
  - ca-certificates
  - gnupg
  - apparmor-utils
  - iptables
  - chrony

common_kernel_modules:
  - br_netfilter
  - overlay

common_sysctls:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
  net.ipv4.conf.all.arp_announce: 2
  net.ipv4.conf.all.arp_ignore: 1
