---
- name: restart kube-vip pod
  ansible.builtin.shell: |
    /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml \
      -n kube-system delete pod kube-vip --ignore-not-found --grace-period=10
  failed_when: false
  changed_when: false
